=== Super12138/AY-Questionnaires-DB/questionnaire-schema.json
{"$schema":"http://json-schema.org/draft-07/schema#","title":"问心量表文件 文件结构","type":"object","properties":{"name":{"description":"量表名称","type":"string"},"description":{"description":"量表描述","type":"string"},"answerTips":{"description":"作答提示","type":"string"},"resultTips":{"description":"结果解读说明","type":"string"},"references":{"description":"相关参考及引用","type":"array","items":{"type":"string"}},"options":{"description":"量表选项","type":"array","items":{"type":"object","properties":{"name":{"description":"选项内容","type":"string"},"score":{"description":"选项分值","type":"number"}},"required":["name","score"]}},"questions":{"description":"量表题目","type":"array","items":{"type":"object","properties":{"groupId":{"description":"题目组 Id","type":"number"},"content":{"description":"题目内容","type":"string"},"reverse":{"description":"开启反向评分（即把量表要求的选项分值在本题反转，但不反转选项内容）","type":"boolean"}},"required":["groupId","content"]}},"scoring":{"description":"评分标准及评分计算方法","type":"array","items":{"type":"object","properties":{"groupId":{"description":"评分组 Id（需与题目所分配的组 Id 对应)","type":"number"},"name":{"description":"当前评分组名称","type":"string"},"method":{"description":"分数计算方法，目前支持计算总和、平均值、总和的倍数（分为乘和除，具体倍率写在 “,” 后面）","type":"string","enum":["plus","average","multiply, ","division, "]},"ranges":{"description":"分值范围","type":"array","items":{"type":"object","properties":{"name":{"description":"当前分值范围名称","type":"string"},"min":{"description":"当前范围最小值（可以取等）","type":"number"},"max":{"description":"当前范围最大值（可以取等）","type":"number"},"color":{"description":"分值范围的颜色（用于分级）","type":"string","enum":["green","yellow","orange","red"]}},"required":["name","min","max"]}}},"required":["groupId","name","method","ranges"]}}},"required":["name","description","answerTips","references","options","questions","scoring"]}

=== Super12138/AY-Questionnaires-DB/questionnaires/bsi18.json
{
    "name": "BSI-18（简明症状量表-18）",
    "description": "BSI-18（Brief Symptom Inventory-18）是由 Derogatis (2001) 基于 SCL-90 量表和 BSI-51 修订而成的简版问卷。它可以测量躯体化、抑郁和焦虑3个方面的症状。相比 SCL-90 作答时间缩短，可以便捷的筛查临床和社区人群。",
    "answerTips": "在随后的题目中有一些关于你身心状况的描述，请根据最近1周内下述情况影响你的实际感觉，选择相应的选项。",
    "resultTips": "下方每个因子的分数均在6-30分之间；每个因子的分数越高，表明该项症状越严重。",
    "references": [
        "常用心理评估量表手册（第3版）"
    ],
    "options": [
        {
            "name": "无",
            "score": 1
        },
        {
            "name": "轻度",
            "score": 2
        },
        {
            "name": "中度",
            "score": 3
        },
        {
            "name": "比较严重",
            "score": 4
        },
        {
            "name": "严重",
            "score": 5
        }
    ],
    "questions": [
        {
            "groupId": 1,
            "content": "头晕或晕倒"
        },
        {
            "groupId": 2,
            "content": "对事物不感兴趣"
        },
        {
            "groupId": 3,
            "content": "神经过敏，心中不踏实"
        },
        {
            "groupId": 1,
            "content": "胸痛"
        },
        {
            "groupId": 2,
            "content": "感到孤独"
        },
        {
            "groupId": 3,
            "content": "感到紧张或容易紧张"
        },
        {
            "groupId": 1,
            "content": "恶心或胃部不舒服"
        },
        {
            "groupId": 2,
            "content": "感到苦闷"
        },
        {
            "groupId": 3,
            "content": "无缘无故地突然感到害怕"
        },
        {
            "groupId": 1,
            "content": "呼吸有困难"
        },
        {
            "groupId": 2,
            "content": "感到自己没有什么价值"
        },
        {
            "groupId": 3,
            "content": "感到一阵阵恐惧或惊恐"
        },
        {
            "groupId": 1,
            "content": "身体发麻或感到刺痛"
        },
        {
            "groupId": 2,
            "content": "感到没有前途、没有希望"
        },
        {
            "groupId": 3,
            "content": "感到坐立不安、心神不宁"
        },
        {
            "groupId": 1,
            "content": "感到身体的某一部分软弱无力"
        },
        {
            "groupId": 2,
            "content": "想结束自己的生命"
        },
        {
            "groupId": 3,
            "content": "感到害怕"
        }
    ],
    "scoring": [
        {
            "groupId": 1,
            "name": "躯体化症状",
            "method": "plus",
            "ranges": [
                {
                    "name": "",
                    "min": 0,
                    "max": 30
                }
            ]
        },
        {
            "groupId": 2,
            "name": "抑郁",
            "method": "plus",
            "ranges": [
                {
                    "name": "",
                    "min": 0,
                    "max": 30
                }
            ]
        },
        {
            "groupId": 3,
            "name": "焦虑",
            "method": "plus",
            "ranges": [
                {
                    "name": "",
                    "min": 0,
                    "max": 30
                }
            ]
        }
    ]
}

=== Super12138/AY-Questionnaires-DB/questionnaires/gad7.json
{"$schema":"../questionnaire-schema.json","name":"GAD-7（广泛性焦虑）量表","description":"GAD-7（Generalized Anxiety Disorder-7）心理状况筛查量表是一种常用于评估广泛性焦虑障碍的工具。该量表由七个问题组成，用于评估受访者在过去两周内的焦虑症状频率和严重程度。通过计分的方式，可以快速了解一个人是否存在焦虑症状及其严重程度。","answerTips":"在过去的2周里，你在生活中有多久对以下问题感到困扰？","references":["https://m.medsci.cn/scale/show.do?id=582f1065a7","https://psych.dxy.cn/article/487819","https://cmhadb.cma-cmc.com.cn/know/v/articleDetail/20/25986.html"],"options":[{"name":"没有","score":0},{"name":"有几天","score":1},{"name":"一半以上的天数","score":2},{"name":"几乎每天","score":3}],"questions":[{"groupId":1,"content":"感到不安、担心、烦躁或易怒"},{"groupId":1,"content":"无法停止或不能控制的担心"},{"groupId":1,"content":"对各种各样的事情担忧过多"},{"groupId":1,"content":"很紧张，无法放松"},{"groupId":1,"content":"非常焦躁，以致无法静坐"},{"groupId":1,"content":"变得易怒或躁动"},{"groupId":1,"content":"担心有不详的事情发生"}],"scoring":[{"groupId":1,"name":"焦虑","method":"plus","ranges":[{"name":"没有焦虑","color":"green","min":0,"max":4},{"name":"轻度焦虑","color":"yellow","min":5,"max":9},{"name":"中度焦虑","color":"orange","min":10,"max":14},{"name":"严重焦虑","color":"red","min":15,"max":21}]}]}

=== Super12138/AY-Questionnaires-DB/questionnaires/phq9.json
{"$schema":"../questionnaire-schema.json","name":"PHQ-9（患者健康问卷）量表","description":"PHQ-9（Patient Health Questionnaire-9，病人健康问卷）是一个简便、有效的抑郁障碍自评量表。它在抑郁症诊断的辅助和症状严重程度评估方面，均具有良好的信度和效度。","answerTips":"在过去的2周里，你在生活中出现以下症状的频率是多少？","resultTips":"如果你的得分在：<ul><li>0-4分：你没有抑郁，继续加强自我保健，保持好心情</li><li>5-9分：你可能有轻度的抑郁，建议寻求专业的心理帮助</li><li>10-14分：可能有中度抑郁，最好寻求专业的心理帮助</li><li>15-19分：可能有中重度抑郁，建议咨询心理医生或精神科医生</li><li>20-27分：可能有重度抑郁，最好咨询心理医生或精神科医生</li></ul>","references":["http://ssc.sanyau.edu.cn/?article/1089.html","https://dxy.com/article/46430","https://www.ncbi.nlm.nih.gov/pmc/articles/PMC1495268/","https://lczl.med.wanfangdata.com.cn/Home/DocumentDetail?id=sjjbyjsws201306009"],"options":[{"name":"没有","score":0},{"name":"有几天","score":1},{"name":"一半以上的时间","score":2},{"name":"几乎天天","score":3}],"questions":[{"groupId":1,"content":"做事时提不起劲或没有兴趣"},{"groupId":1,"content":"感到心情低落, 沮丧或绝望"},{"groupId":1,"content":"入睡困难、睡不安或睡得过多"},{"groupId":1,"content":"感觉疲倦或没有活力"},{"groupId":1,"content":"食欲不振或吃太多"},{"groupId":1,"content":"觉得自己很糟或觉得自己很失败，或让自己、家人失望"},{"groupId":1,"content":"很难集中注意力，比如读报纸或者看电视"},{"groupId":1,"content":"行动或说话速度慢到已经被别人察觉？或刚好相反——变得比平时更加烦躁或坐立不安，动来动去"},{"groupId":1,"content":"觉得如果自己死了反而会更好，或者有想伤害自己的想法"}],"scoring":[{"groupId":1,"name":"抑郁","method":"plus","ranges":[{"name":"没有抑郁","color":"green","min":0,"max":4},{"name":"轻度抑郁","color":"yellow","min":5,"max":9},{"name":"中度抑郁","color":"orange","min":10,"max":14},{"name":"中重度抑郁","color":"orange","min":15,"max":19},{"name":"重度抑郁","color":"red","min":20,"max":27}]}]}

=== Super12138/AY-Questionnaires-DB/questionnaires/hads.json
{"$schema":"../questionnaire-schema.json","name":"HADS（医院焦虑抑郁量表）","description":"HADS（Hospital anxiety and depression scale，医院焦虑抑郁量表）是一个筛查量表。它的最佳用途是帮助综合医院医生筛查可疑存在焦虑或抑郁症状的患者，对阳性的患者做进一步的深入检查以明确诊断并给予相应的治疗。（注：由于问心的题目文件不能很好的支持设定每个题目的选项，故选项有改动）","answerTips":"情绪在大多数疾病中起着重要作用，如果医生了解您的情绪变化，他们就能给您更多的帮助。请您阅读以下各个条目，并选择其中最符合您上个月以来的情绪选项。对这些问题不要做过多的考虑，立即做出的回答会比考虑后再回答更切合实际。","references":["常用心理评估量表手册（第3版）"],"options":[{"name":"肯定或大多数时候","score":3},{"name":"多数时候","score":2},{"name":"有时","score":1},{"name":"很少或根本没有","score":0}],"questions":[{"groupId":1,"content":"我感到紧张（或痛苦）"},{"groupId":2,"content":"我对以往感兴趣的事情还是有兴趣","reverse":true},{"groupId":1,"content":"我感到有点害怕，好像预感到有什么可怕事情要发生"},{"groupId":2,"content":"我能够哈哈大笑，并看到事物好的一面","reverse":true},{"groupId":1,"content":"我的心中充满烦恼"},{"groupId":2,"content":"我感到愉快","reverse":true},{"groupId":1,"content":"我能够安静而轻松地坐着","reverse":true},{"groupId":2,"content":"我对自己的仪容（打扮自己）失去兴趣"},{"groupId":1,"content":"我有点坐立不安，好像感到非要活动不可"},{"groupId":2,"content":"我对一切都是乐观地向前看","reverse":true},{"groupId":1,"content":"我突然出现恐慌感"},{"groupId":2,"content":"我好像感到情绪在渐渐低落"},{"groupId":1,"content":"我感到有点害怕，好像某个内脏器官变坏了"},{"groupId":2,"content":"我能欣赏一本好书或一项好的广播或电视节目","reverse":true}],"scoring":[{"groupId":1,"name":"焦虑（A）","method":"plus","ranges":[{"name":"无症状","color":"green","min":0,"max":8},{"name":"有症状","color":"red","min":9,"max":21}]},{"groupId":2,"name":"抑郁（D）","method":"plus","ranges":[{"name":"无症状","color":"green","min":0,"max":8},{"name":"有症状","color":"red","min":9,"max":21}]}]}

=== Super12138/AY-Questionnaires-DB/questionnaires/phq9-eng.json
{"$schema":"../questionnaire-schema.json","name":"PHQ-9 (Patient Health Questionnaire-9) 量表","description":"病人健康问卷（Patient Health Questionnaire-9，PHQ-9）是一个简便、有效的抑郁障碍自评量表，在抑郁症诊断的辅助和症状严重程度评估方面，均具有良好的信度和效度。","answerTips":"Over the last 2 weeks, how often have you been bothered by any of the following problems?","references":["https://www.apa.org/depression-guideline/patient-health-questionnaire.pdf","https://patient.info/doctor/patient-health-questionnaire-phq-9"],"options":[{"name":"Not at all","score":0},{"name":"Several days","score":1},{"name":"More than half the days","score":2},{"name":"Nearly every day","score":3}],"questions":[{"groupId":1,"content":"Little interest or pleasure in doing things"},{"groupId":1,"content":"Feeling down, depressed, or hopeless"},{"groupId":1,"content":"Trouble falling or staying asleep, or sleeping too much"},{"groupId":1,"content":"Feeling tired or having little energy"},{"groupId":1,"content":"Poor appetite or overeating"},{"groupId":1,"content":"Feeling bad about yourself — or that you are a failure or have let yourself or your family down"},{"groupId":1,"content":"Trouble concentrating on things, such as reading the newspaper or watching television"},{"id":8,"groupId":1,"content":"Moving or speaking so slowly that other people could have noticed? Or the opposite — being so fidgety or restless that you have been moving around a lot more than usual"},{"id":9,"groupId":1,"content":"Thoughts that you would be better off dead or of hurting yourself in some way"}],"scoring":[{"groupId":1,"name":"Depression","method":"plus","ranges":[{"name":"No depression","color":"green","min":0,"max":4},{"name":"Mild depression","color":"yellow","min":5,"max":9},{"name":"Moderate depression","color":"orange","min":10,"max":14},{"name":"Moderate severe depression","color":"orange","min":15,"max":19},{"name":"Severe depression","color":"red","min":20,"max":27}]}]}

=== Super12138/AY-Questionnaires-DB/questionnaires/srq20.json
{
    "$schema": "../questionnaire-schema.json",
    "name": "SRQ-20（心理健康自评量表）量表",
    "description": "SRQ-20（Self Reporting Questionnaire-20）是一个心理健康的自评量表。它是由世界卫生组织发布的，用于评判心理状况专业工具。同时也被原卫生部的《灾难心理危机干预培训手册》所收录。",
    "answerTips": "以下问题与某些痛苦有关，在过去30日内可能困扰您。如果您觉得问题适合您的情况，并在过去30日内存在，请选择“是”。如果问题不适合您的情况或在过去30日内不存在，请选择“否”。在回答问卷时请不要与任何人讨论。如果您不能确定该如何回答问题，请尽量给出您认为的最恰当的回答。",
    "references": [
        "https://iris.who.int/handle/10665/61113",
        "https://cmhadb.cma-cmc.com.cn/know/v/articleDetail/20/25981.html"
    ],
    "options": [
        {
            "name": "是",
            "score": 1
        },
        {
            "name": "否",
            "score": 0
        }
    ],
    "questions": [
        {
            "groupId": 1,
            "content": "您是否经常头痛？"
        },
        {
            "groupId": 1,
            "content": "您是否食欲差？"
        },
        {
            "groupId": 1,
            "content": "您是否睡眠差？"
        },
        {
            "groupId": 1,
            "content": "您是否易受惊吓？"
        },
        {
            "groupId": 1,
            "content": "您是否手抖？"
        },
        {
            "groupId": 1,
            "content": "您是否感觉不安、紧张或担忧？"
        },
        {
            "groupId": 1,
            "content": "您是否消化不良？"
        },
        {
            "groupId": 1,
            "content": "您是否思维不清晰？"
        },
        {
            "groupId": 1,
            "content": "您是否感觉不快乐？"
        },
        {
            "groupId": 1,
            "content": "您是否比原来哭得多？"
        },
        {
            "groupId": 1,
            "content": "您是否发现很难从日常活动中得到乐趣？"
        },
        {
            "groupId": 1,
            "content": "您是否发现自己很难做决定？"
        },
        {
            "groupId": 1,
            "content": "日常工作是否令您感到痛苦？"
        },
        {
            "groupId": 1,
            "content": "您在生活中是否不能起到应起的作用？"
        },
        {
            "groupId": 1,
            "content": "您是否丧失了对事物的兴趣？"
        },
        {
            "groupId": 1,
            "content": "您是否感到自己是个无价值的人？"
        },
        {
            "groupId": 1,
            "content": "您头脑中是否出现过结束自己生命的想法？"
        },
        {
            "groupId": 1,
            "content": "您是否什么时候都感到累？"
        },
        {
            "groupId": 1,
            "content": "您是否感到胃都不适？"
        },
        {
            "groupId": 1,
            "content": "您是否容易疲劳？"
        }
    ],
    "scoring": [
        {
            "groupId": 1,
            "name": "总分",
            "method": "plus",
            "ranges": [
                {
                    "name": "正常范围",
                    "color": "green",
                    "min": 0,
                    "max": 7
                },
                {
                    "name": "可能存在情感痛苦",
                    "color": "red",
                    "min": 8,
                    "max": 20
                }
            ]
        }
    ]
}

=== Super12138/AY-Questionnaires-DB/questionnaires/gad7-eng.json
{"$schema":"../questionnaire-schema.json","name":"GAD-7 (Generalized Anxiety Disorder-7) 量表","description":"GAD-7（Generalized Anxiety Disorder-7）心理状况筛查量表是一种常用于评估广泛性焦虑障碍的工具。该量表由七个问题组成，用于评估受访者在过去两周内的焦虑症状频率和严重程度。通过计分的方式，可以快速了解一个人是否存在焦虑症状及其严重程度。","answerTips":"Over the last 2 weeks, how often have you been bothered by the following problems?","references":["https://arc.psych.wisc.edu/self-report/generalized-anxiety-disorder-gad7/","https://patient.info/doctor/generalised-anxiety-disorder-assessment-gad-7"],"options":[{"name":"Not at all","score":0},{"name":"Several days","score":1},{"name":"More than half the days","score":2},{"name":"Nearly every day","score":3}],"questions":[{"groupId":1,"content":"Feeling nervous, anxious or on edge"},{"groupId":1,"content":"Not being able to or control worrying"},{"groupId":1,"content":"Worrying about too much of different things"},{"groupId":1,"content":"Trouble relaxing"},{"groupId":1,"content":"Being so restless that it is hard to sit still"},{"groupId":1,"content":"Being easily annoyed or irritable"},{"groupId":1,"content":"Feeling afraid as if something awful might happen"}],"scoring":[{"groupId":1,"name":"Anxiety","method":"plus","ranges":[{"name":"No anxiety","color":"green","min":0,"max":4},{"name":"Mild anxiety","color":"yellow","min":5,"max":9},{"name":"Moderate anxiety","color":"orange","min":10,"max":14},{"name":"Severe anxiety","color":"red","min":15,"max":21}]}]}

=== Super12138/AY-Questionnaires-DB/questionnaires/scl90-middle.json
{"$schema":"../questionnaire-schema.json","name":"SCL-90（90 项症状清单，中学生常模）","description":"SCL-90（Symptom Checklist-90）是一个有 90 项的症状自评量表。它用来衡量门诊病人自觉症状的严重程度。它一共有9个因子，覆盖面较广，可以准确地反映被试的自觉症状和问题及其严重程度和变化。","answerTips":"本表结果评判采用中国中学生（2002）常模。下面题目列出了你可能存在的症状或困扰。请仔细阅读每一项，并根据你最近1周（包括今天）的实际感觉选择与你的情况最符合的选项。","resultTips":"在下方的表格中列出了总分和每个因子的得分。如果总分超过 160 分，或阳性项目数超过 43 个，或任意因子分大于 2 分，则需要进一步检查确认。 <br> <p>因子解释：</p> <ol> <li>躯体化：该因子主要反映主观的身体不适感；</li> <li>强迫症状：反映临床上的强迫症状群；</li> <li>人际关系敏感：主要指某些个人不自在感和自卑感，尤其是在与他人相比较时更突出； <li>抑郁：反映与临床上抑郁症状群相联系的广泛的概念； <li>焦虑：指在临床上明显与焦虑症状相联系的精神症状及体验；</li> <li>敌对：主要从思维、情感及行为3个方面来反映病人的敌对表现；</li> <li>恐怖：它与传统的恐怖状态或广场恐怖所反映的内容基本一致；</li> <li>偏执：主要是指猜疑和关系妄想等；</li> <li>精神病性：其中有幻听、思维播散、被洞悉感等反映精神分裂样症状项目。</li> </ol>","references":["常用心理评估量表手册（第3版）","https://www.gench.edu.cn/xlhp/2013/0704/c2343a18368/page.psp","https://joukovaara.github.io/scale/SCL90.html","https://arc.psych.wisc.edu/self-report/symptom-checklist-90-scl90/"],"options":[{"name":"没有","score":1},{"name":"轻度","score":2},{"name":"中度","score":3},{"name":"偏重","score":4},{"name":"严重","score":5}],"questions":[{"groupId":1,"content":"头痛"},{"groupId":5,"content":"神经过敏，心中不踏实"},{"groupId":2,"content":"头脑中有不必要的想法或字句盘旋"},{"groupId":1,"content":"头昏或昏倒"},{"groupId":4,"content":"对异性的兴趣减退"},{"groupId":3,"content":"对旁人责备求全"},{"groupId":9,"content":"感到别人能控制你的思想"},{"groupId":8,"content":"责怪别人制造麻烦"},{"groupId":2,"content":"忘性大"},{"groupId":2,"content":"担心自己的衣饰整齐及仪态的端正"},{"groupId":6,"content":"容易烦恼和激动"},{"groupId":1,"content":"胸痛"},{"groupId":7,"content":"害怕空旷的场所或街道"},{"groupId":4,"content":"感到自己的精力下降，活动减慢"},{"groupId":4,"content":"想结束自己的生命"},{"groupId":9,"content":"听到旁人听不到的声音"},{"groupId":5,"content":"发抖"},{"groupId":8,"content":"感到大多数人都不可信任"},{"groupId":10,"content":"胃口不好"},{"groupId":4,"content":"容易哭泣"},{"groupId":3,"content":"同异性相处时感到害羞不自在"},{"groupId":4,"content":"感到受骗，中了圈套或有人想抓您"},{"groupId":5,"content":"无缘无故地突然感到害怕"},{"groupId":6,"content":"自己不能控制地大发脾气"},{"groupId":7,"content":"害怕单独出门"},{"groupId":4,"content":"经常责怪自己"},{"groupId":1,"content":"腰痛"},{"groupId":2,"content":"感到难以完成任务"},{"groupId":4,"content":"感到孤独"},{"groupId":4,"content":"感到苦闷"},{"groupId":4,"content":"过分担忧"},{"groupId":4,"content":"对事物不感兴趣"},{"groupId":5,"content":"感到害怕"},{"groupId":3,"content":"我的感情容易受到伤害"},{"groupId":9,"content":"旁人能知道你的私下想法"},{"groupId":3,"content":"感到别人不理解你、不同情你"},{"groupId":3,"content":"感到人们对你不友好，不喜欢你"},{"groupId":2,"content":"做事必须做得很慢以保证做得正确"},{"groupId":5,"content":"心跳得很厉害"},{"groupId":1,"content":"恶心或胃部不舒服"},{"groupId":3,"content":"感到比不上他人"},{"groupId":1,"content":"肌肉酸痛"},{"groupId":8,"content":"感到有人在监视你、谈论你"},{"groupId":10,"content":"难以入睡"},{"groupId":2,"content":"做事必须反复检查"},{"groupId":2,"content":"难以做出决定"},{"groupId":7,"content":"怕乘电车、公共汽车、地铁或火车"},{"groupId":1,"content":"呼吸有困难"},{"groupId":1,"content":"一阵阵发冷或发热"},{"groupId":7,"content":"因为感到害怕而避开某些东西、场合或活动"},{"groupId":2,"content":"脑子变空了"},{"groupId":1,"content":"身体发麻或刺痛"},{"groupId":1,"content":"喉咙有梗阻感"},{"groupId":4,"content":"感到没有前途、没有希望"},{"groupId":2,"content":"不能集中注意力"},{"groupId":1,"content":"感到身体某一部分软弱无力"},{"groupId":5,"content":"感到紧张或容易紧张"},{"groupId":1,"content":"感到手或脚发重"},{"groupId":10,"content":"想到死亡的事"},{"groupId":10,"content":"吃得太多"},{"groupId":3,"content":"当别人看着你或谈论你时感到不自在"},{"groupId":9,"content":"有一些不属于你自己的想法"},{"groupId":6,"content":"有想打人或伤害他人的冲动"},{"groupId":10,"content":"醒得太早"},{"groupId":2,"content":"必须反复洗手、点数目或触摸某些东西"},{"groupId":10,"content":"睡得不稳不深"},{"groupId":6,"content":"有想摔坏或破坏东西的冲动"},{"groupId":8,"content":"有一些别人没有的想法或念头"},{"groupId":3,"content":"感到对别人神经过敏"},{"groupId":7,"content":"在商店或电影院等人多的地方感到不自在"},{"groupId":4,"content":"感到任何事情都很困难"},{"groupId":5,"content":"感到一阵阵恐惧或惊恐"},{"groupId":3,"content":"感到在公共场合吃东西很不舒服"},{"groupId":6,"content":"经常与人争论"},{"groupId":7,"content":"单独一人时神经很紧张"},{"groupId":8,"content":"感到别人对你的成绩没有作出恰当的评价"},{"groupId":9,"content":"即使和别人在一起也感到孤独"},{"groupId":5,"content":"感到坐立不安、心神不定"},{"groupId":4,"content":"感到自己没有什么价值"},{"groupId":5,"content":"感到熟悉的东西变得陌生或不像是真的"},{"groupId":6,"content":"大叫或摔东西"},{"groupId":7,"content":"害怕会在公共场合昏倒"},{"groupId":8,"content":"感到别人想占你的便宜"},{"groupId":9,"content":"为一些有关“性”的想法而苦恼"},{"groupId":9,"content":"你认为应该因为自己的过错而受到惩罚"},{"groupId":5,"content":"想着要赶快把事情做完"},{"groupId":9,"content":"感到自己的身体有严重问题"},{"groupId":9,"content":"从未感到和其他人很亲近"},{"groupId":10,"content":"感到自己有罪"},{"groupId":9,"content":"感到自己的脑子有毛病"}],"scoring":[{"groupId":1,"name":"躯体化","method":"average","ranges":[{"name":"正常范围","color":"green","min":0,"max":2.2},{"name":"中度","color":"yellow","min":2.21,"max":2.81},{"name":"严重","color":"red","min":2.82,"max":5}]},{"groupId":2,"name":"强迫症状","method":"average","ranges":[{"name":"正常范围","color":"green","min":0,"max":2.2},{"name":"中度","color":"yellow","min":2.82,"max":3.53},{"name":"严重","color":"red","min":3.54,"max":5}]},{"groupId":3,"name":"人际关系敏感","method":"average","ranges":[{"name":"正常范围","color":"green","min":0,"max":2.5},{"name":"中度","color":"yellow","min":2.51,"max":3.17},{"name":"严重","color":"red","min":3.18,"max":5}]},{"groupId":4,"name":"抑郁","method":"average","ranges":[{"name":"正常范围","color":"green","min":0,"max":2.48},{"name":"中度","color":"yellow","min":2.49,"max":3.18},{"name":"严重","color":"red","min":3.19,"max":5}]},{"groupId":5,"name":"焦虑","method":"average","ranges":[{"name":"正常范围","color":"green","min":0,"max":2.44},{"name":"中度","color":"yellow","min":2.45,"max":3.12},{"name":"严重","color":"red","min":3.13,"max":5}]},{"groupId":6,"name":"敌对","method":"average","ranges":[{"name":"正常范围","color":"green","min":0,"max":2.55},{"name":"中度","color":"yellow","min":2.56,"max":3.28},{"name":"严重","color":"red","min":3.29,"max":5}]},{"groupId":7,"name":"恐怖","method":"average","ranges":[{"name":"正常范围","color":"green","min":0,"max":2.14},{"name":"中度","color":"yellow","min":2.15,"max":2.74},{"name":"严重","color":"red","min":2.75,"max":5}]},{"groupId":8,"name":"偏执","method":"average","ranges":[{"name":"正常范围","color":"green","min":0,"max":2.42},{"name":"中度","color":"yellow","min":2.43,"max":3.09},{"name":"严重","color":"red","min":3.1,"max":5}]},{"groupId":9,"name":"精神病性","method":"average","ranges":[{"name":"正常范围","color":"green","min":0,"max":2.29},{"name":"中度","color":"yellow","min":2.3,"max":2.9},{"name":"严重","color":"red","min":2.91,"max":5}]},{"groupId":10,"name":"附加项目","method":"average","ranges":[{"name":"不做评价","min":0,"max":10}]}]}
